version: '3.7'

services:
  postgres:
    image: "postgres:latest"
    ports:
     - "5432:5432"
    env_file:
      - ./simple_notes/simple_notes/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - staticfiles:/usr/src/app/assets
    depends_on:
      - postgres

volumes:
  staticfiles:
  postgres-data:
