# Generated by Django 3.1.2 on 2020-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
