# Generated by Django 3.2.4 on 2021-06-16 15:50

import django.db.models.deletion
from django.db import migrations, models

import notes.utils


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("task_id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("note", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notes.note", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivationToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(default=notes.utils.generate_token, max_length=32, unique=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notes.profile", unique=True),
                ),
            ],
        ),
    ]
