# Generated by Django 3.1.2 on 2020-10-08 05:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20201006_0607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicsharednote',
            unique_together={('user', 'note')},
        ),
    ]
