# Generated by Django 3.2.4 on 2021-06-09 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_auto_20201008_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], default='en', max_length=20)),
                ('theme', models.CharField(choices=[('default', 'Default'), ('lux', 'Lux'), ('pulse', 'Pulse'), ('sandstone', 'Sandstone')], default='default', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
